const a = [
  {
    grant: 4,
    icon: "mdi-play",
    newTap: false,
    subItems: [
      {
        grant: 0,
        icon: "mdi-",
        newTab: false,
        subItems: [],
        title: "greeting",
        to: "/basic/b",
        isHide: false,
        show: false,
        spread: "arrow_right",
      },
      {
        grant: 2,
        icon: "mdi-playlist-check",
        newTap: false,
        subItems: [
          {
            grant: 2,
            icon: "mdi-flag",
            newTap: false,
            subItems: [],
            title: "Team",
            to: "/basic/b",
            show: false,
            isHide: false,
            spread: "arrow_right",
          },
        ],
        title: "List",
        to: "/",
        show: false,
        isHide: false,
        spread: "arrow_right",
      },
      {
        grant: 0,
        icon: "mdi-",
        newTab: false,
        subItems: [],
        title: "테스트",
        to: "/board/test",
        isHide: false,
        show: false,
        spread: "arrow_right",
      },
    ],
    title: "SNS",
    to: "/ex",
    show: false,
    isHide: false,
    spread: "arrow_drop_down",
  },
  {
    grant: 2,
    icon: "mdi-clock",
    newTap: false,
    subItems: [
      {
        grant: 10,
        icon: "mdi-car",
        newTab: false,
        subItems: [],
        title: "관리용",
        to: "/board/innerBasic",
        isHide: false,
        show: false,
        spread: "arrow_right",
      },
      {
        grant: 0,
        icon: "mdi-help",
        newTap: false,
        subItems: [],
        title: "Dashboard",
        to: "/",
        show: false,
        isHide: false,
        spread: "arrow_right",
      },
    ],
    title: "My Work",
    to: "/",
    show: false,
    isHide: false,
    spread: "arrow_right",
  },
  {
    grant: 2,
    icon: "mdi-projector",
    newTap: false,
    subItems: [
      {
        grant: 3,
        icon: "mdi-pen",
        newTap: false,
        subItems: [],
        title: "Vue",
        to: "/main",
        show: false,
        isHide: true,
        spread: "arrow_right",
      },
      {
        grant: 10,
        icon: "mdi-pen",
        newTap: false,
        subItems: [],
        title: "Javascript",
        to: "/javascript",
        show: false,
        isHide: true,
        spread: "arrow_right",
      },
    ],
    title: "My Project",
    to: "/projects",
    show: false,
    isHide: true,
    spread: "arrow_right",
  },
  {
    grant: 0,
    icon: "mdi-car",
    newTab: false,
    subItems: [
      {
        icon: "",
        title: "팬들 애도 물결",
        to: "/board/sub/?wr_id=2",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
        spread: "arrow_right",
      },
      {
        icon: "",
        title: "美 ''자이언트 스텝'' ",
        to: "/board/sub/?wr_id=1",
        grant: 0,
        subItems: [
          {
            grant: 0,
            icon: "mdi-",
            newTab: false,
            subItems: [],
            title: "test",
            to: "/team",
            isHide: false,
            show: false,
            spread: "arrow_right",
          },
        ],
        newTab: false,
        show: false,
        spread: "arrow_right",
      },
    ],
    title: "서브메뉴",
    to: "/board/sub",
    isHide: false,
    show: false,
    spread: "arrow_right",
  },
  {
    grant: 0,
    icon: "mdi-message",
    newTab: false,
    subItems: [
      {
        icon: "",
        title: "정보보호",
        to: "/board/infoGallery/?cate=정보보호",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
        spread: "arrow_right",
      },
      {
        icon: "",
        title: "금융정보보호",
        to: "/board/infoGallery/?cate=금융정보보호",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
        spread: "arrow_right",
      },
      {
        icon: "",
        title: "인공지능",
        to: "/board/infoGallery/?cate=인공지능",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
        spread: "arrow_right",
      },
      {
        icon: "",
        title: "포랜식",
        to: "/board/infoGallery/?cate=포랜식",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
        spread: "arrow_right",
      },
    ],
    title: "정보보안",
    to: "/board/infoGallery",
    isHide: false,
    show: false,
    spread: "arrow_right",
  },
];
