const a = [
  {
    grant: 4,
    icon: "mdi-play",
    newTap: false,

    title: "SNS",
    to: "/ex",
    show: false,
    isHide: false,
    subItems: [
      {
        grant: 2,
        icon: "mdi-playlist-check",
        newTap: false,
        subItems: [],
        title: "List",
        to: "/list",
        show: false,
        isHide: false,
      },
    ],
  },
  {
    grant: 2,
    icon: "mdi-clock",
    newTap: false,
    subItems: [
      {
        grant: 0,
        icon: "mdi-help",
        newTap: false,
        subItems: [],
        title: "Dashboard",
        to: "/",
        show: false,
        isHide: true,
      },
    ],
    title: "My Work",
    to: "/",
    show: false,
    isHide: true,
  },
  {
    grant: 2,
    icon: "mdi-flag",
    newTap: false,
    subItems: [],
    title: "Team",
    to: "/team",
    show: false,
    isHide: false,
  },
  {
    grant: 2,
    icon: "mdi-projector",
    newTap: false,
    subItems: [
      {
        grant: 3,
        icon: "mdi-pen",
        newTap: false,
        subItems: [],
        title: "Vue",
        to: "/main",
        show: false,
        isHide: true,
      },
      {
        grant: 10,
        icon: "mdi-pen",
        newTap: false,
        subItems: [],
        title: "Javascript",
        to: "/javascript",
        show: false,
        isHide: true,
      },
    ],
    title: "My Project",
    to: "/projects",
    show: false,
    isHide: true,
  },
  {
    grant: 0,
    icon: "mdi-",
    newTab: false,
    subItems: [],
    title: "greeting",
    to: "/board/greeting",
    isHide: false,
    show: false,
  },
  {
    grant: 0,
    icon: "mdi-car",
    newTab: false,
    subItems: [
      {
        icon: "",
        title: "팬들 애도 물결",
        to: "/board/sub/?wr_id=2",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
      },
      {
        icon: "",
        title: "美 ''자이언트 스텝'' ",
        to: "/board/sub/?wr_id=1",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
      },
    ],
    title: "서브메뉴",
    to: "/board/sub",
    isHide: false,
    show: false,
  },
  {
    grant: 0,
    icon: "mdi-message",
    newTab: false,
    subItems: [
      {
        icon: "",
        title: "정보보호",
        to: "/board/infoGallery/?cate=정보보호",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
      },
      {
        icon: "",
        title: "금융정보보호",
        to: "/board/infoGallery/?cate=금융정보보호",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
      },
      {
        icon: "",
        title: "인공지능",
        to: "/board/infoGallery/?cate=인공지능",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
      },
      {
        icon: "",
        title: "포랜식",
        to: "/board/infoGallery/?cate=포랜식",
        grant: 0,
        subItems: [],
        newTab: false,
        show: false,
      },
    ],
    title: "정보보안",
    to: "/board/infoGallery",
    isHide: false,
    show: false,
  },
  {
    grant: 0,
    icon: "mdi-",
    newTab: false,
    subItems: [],
    title: "테스트",
    to: "/board/test",
    isHide: false,
    show: false,
  },
  {
    grant: 10,
    icon: "mdi-car",
    newTab: false,
    subItems: [],
    title: "관리용",
    to: "/board/innerBasic",
    isHide: false,
    show: false,
  },
  {
    grant: 0,
    icon: "mdi-",
    newTab: false,
    subItems: [],
    title: "test",
    to: "/team",
    isHide: false,
    show: false,
  },
];
